version: '3'

services:
  frontend:
    container_name : frontend_container
    image: pimbuthia/yolo-frontend:1.0.1
    ports:
      - 3000:3000    
    depends_on:
      - backendy
    stdin_open: true
  backendy:
    container_name: backend_container
    image: pimbuthia/yolo-backend:1.0.1   
    ports: 
      - 5000:5000
    environment:
      MONGODB_URI: 'mongodb://yolomy:yolomy@172.100.0.3:27017'
    networks:
      backend-net:
        ipv4_address: 172.100.0.2     
    depends_on:
      - database
    volumes:
      - .:/app
  database:
    container_name: backend_database    
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: yolomy
      MONGO_INITDB_ROOT_PASSWORD: yolomy
    ports:
      - 27017:27017
    networks:
      backend-net:
        ipv4_address: 172.100.0.3
    
networks:
  backend-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
